name: release

on: 
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        required: false
        default: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: ${{ inputs.dry_run }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
